/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wj_testretrfittwoencode_XXTEA */

#ifndef _Included_com_wj_testretrfittwoencode_XXTEA
#define _Included_com_wj_testretrfittwoencode_XXTEA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wj_testretrfittwoencode_XXTEA
 * Method:    getNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wj_testretrfittwoencode_XXTEA_getNativeString
  (JNIEnv *, jclass);

/*
 * Class:     com_wj_testretrfittwoencode_XXTEA
 * Method:    getKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wj_testretrfittwoencode_XXTEA_getKey
  (JNIEnv *, jclass);

/*
 * Class:     com_wj_testretrfittwoencode_XXTEA
 * Method:    getIv
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_wj_testretrfittwoencode_XXTEA_getIv
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
